### ISSUE TITLE
[BUG] Fleeca Great Ocean Door Issues

### ISSUE THREAD

**Issue by Quagel** [dennrick/LineageRoleplay#100]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    Vault door did not open after completing the hack. Unsure if this is intentional or a bug as a result of changes during the latest updates. 
Display message when trying to hack the door again stated "The security lock is active, the door cannot be opened at the moment..." and the bank was timed out after in the 'Page Up' muscle.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Go to Fleeca Bank on Great Ocean
    2. Complete hack.
   
**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Vault door to open after completing the hack.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    N/A

**Additional context** *(Add any other context about the problem here):*
    
    N/A
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    N/A

**Comment by dennrick** [comment]
Resolved with 6/27 updates
