### ISSUE TITLE
[FEATURE] More closet save slots

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#102]
## [Feature Request]

**Is your feature request related to a problem?** *If so, describe in detail:*

> More closet save slots please

**Describe the solution you'd like to see:**

> add save slots

**Describe alternatives you've considered:**

> wear the same outfits

**Additional context**

> it would be nice for players to be able to save more outfits

**Comment by dennrick** [comment]
Planning an increase to 10 once we confirm the bugs have been squashed with this.

**Comment by dennrick** [comment]
this is now done.
