### ISSUE TITLE
[BUG] Unable to Check into Pillbox

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#104]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

> have been unable to check into pillbox have not heard of anybody else with the issue

In this and other instances it was food related death

Error message : Unable to take action

**To Reproduce** *(Steps to reproduce the behavior):*
  
> I check into hospital receive error seen in top right corner of screenshot

**Expected behavior** *(A clear and concise description of what you expected to happen):*

> checkin and be revived

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   

![FiveM_b2060_GTAProcess_xPXVec0FcU](https://user-images.githubusercontent.com/82202019/119277022-23052c80-bbd2-11eb-8b89-950c91804ccc.jpg)
![FiveM_b2060_GTAProcess_IknsEUAJqb](https://user-images.githubusercontent.com/82202019/119277024-24cef000-bbd2-11eb-9c3f-98a7725a7ab1.jpg)

**Comment by dennrick** [comment]
Is this still an issue for you, @daddyDUBZ?  I'm unable to replicate.

**Comment by daddyDUBZ** [comment]
It is not sorry for the delayed response.  I ll close this ticket
