### ISSUE TITLE
[BUG] angrily taking off clothes

### ISSUE THREAD

**Issue by overlordrockz** [dennrick/LineageRoleplay#105]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    When taking off or putting on clothes with the F6 menu, you shadow box. I am unsure when this bug first appeared but I noticed today when taking off a hat.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Open the F6 menu
    2. Click on an item of clothing
    3. See error

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    You would take the item of clothing off without fighting a ghost.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by daddyDUBZ** [comment]
Normal left click function(punch) should be suppressed while in clothing menu.

**Comment by dennrick** [comment]
@overlordrockz and @daddyDUBZ are you having this all the time and on any piece of clothing?  I'm not having this on live server as of yet when testing today.

**Comment by overlordrockz** [comment]
myself and theemrpink were both experiencing this yesterday on our PD characters but it seemed to fix itself when I switched characters. Today I have not noticed the error.
