### ISSUE TITLE
[SOP] Silver Goblet Bar and Grill

### ISSUE THREAD

**Issue by overlordrockz** [dennrick/LineageRoleplay#107]
## [SOP Request]

**General description of your SOP request:**

    I would like to open a restaurant in the city with one of my characters at postal 150 near the impound lot.

**Would people work/affiliate with this SOP?**

    Yes, at least 4 employees.

**What permissions, scripts, interiors, special vehicles etc. are required?**

    The building would need locks added to some of the doors (specified in the Google Doc), a point of sale would need to be added at the counter, and a place in the kitchen would need to be added to make the food. I would also like to change the flooring to a tiled floor that has no broken tiles and, if possible, remove the dirt and grime from the walls and ceilings. The locks would only be able to be unlocked by those that work in the establishment.
I will be updating this when i get a uniform figured out.

**SOP Request**

    https://docs.google.com/document/d/1YLVbYwW7Y1K1saO-llN5IYiykiuyTwjkOVOb1fydN18/edit?usp=sharing

**Comment by overlordrockz** [comment]
The proposed Uniform that I would like is: Hat 61 texture 6, Jacket 11 texture 0, Undershirt 22 texture 4, Pants 28 texture 8, Shoes 20 texture 7.

**Comment by dennrick** [comment]
SOP Submissions are once again handled on Discord.  We already had another SOP in for this location as well so this location won't be available.
