### ISSUE TITLE
[FEATURE] Relocate Garage

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#109]
## [Feature Request]

**Is your feature request related to a problem?** *If so, describe in detail:*

> It would be nice to see the addition of a garage on or around the pier

**Describe the solution you'd like to see:**

> Public garage addition/relocation.  
Relocate spanish ave parking lot (postal342) to postal 610 See screenshots

**Describe alternatives you've considered:**

    Enter details of alternative solutions here.

**Additional context**

![image](https://user-images.githubusercontent.com/82202019/119760985-e0588400-be5f-11eb-880a-db8be6bcfa00.png)

![image](https://user-images.githubusercontent.com/82202019/119761079-05e58d80-be60-11eb-9565-7de3f37a3080.png)

**Comment by dennrick** [comment]
Added a garage at pier at this location in PTR.  Will look at removing the other in a future update.
