### ISSUE TITLE
[BUG] Cell Phone Call notifications

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#110]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

> Notifications do not disappear from screen

**To Reproduce** *(Steps to reproduce the behavior):*
  
> miss a call
notification remains w/ no way to remove
see screenshot

**Expected behavior** *(A clear and concise description of what you expected to happen):*

> Notification removes after a time on screen

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
![image](https://user-images.githubusercontent.com/82202019/120002456-b56a4f00-bf89-11eb-83fb-82ca977f985e.png)

**Comment by dennrick** [comment]
Should be resolved.  Let us know if it isn't
