### ISSUE TITLE
[BUG] Hardware Store/Other Indicator Position

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#111]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

> Adjust display height of hardware store indicator
3020 Nearest Postal

**Will add more locations to this ticket as located and tag developer as necessary**

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1.see screenshots

    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
![image](https://user-images.githubusercontent.com/82202019/120003311-7ab4e680-bf8a-11eb-8c7c-275158bce777.png)

**Comment by daddyDUBZ** [comment]
**POSTAL 130**

![image](https://user-images.githubusercontent.com/82202019/120024694-6aaa0080-bfa4-11eb-9b26-70e95fd3db45.png)

**Comment by dennrick** [comment]
Both of these have been adjusted in the PTR.  Leaving open for additionals.

**Comment by daddyDUBZ** [comment]
Clothing store postal 908 store indicator position in ground @dennrick @MjrDeathAdder 


![image](https://user-images.githubusercontent.com/82202019/120570884-e6091900-c3cd-11eb-8bed-c1fdc2198160.png)

**Comment by dennrick** [comment]
908 Sorted

**Comment by daddyDUBZ** [comment]
908 Hardware store indicator @dennrick 

![image](https://user-images.githubusercontent.com/82202019/120948786-dbb18c80-c6f7-11eb-8b5d-8e1b2be8ba8b.png)

**Comment by dennrick** [comment]
This was patched.  Going to close this out now.  Just re-open if you find more.

**Comment by daddyDUBZ** [comment]
908 hardware pin is still in the ground

**Comment by daddyDUBZ** [comment]
908 hardware pin is still in ground.
