### ISSUE TITLE
[BUG] Saved Outfit on Disconnect

### ISSUE THREAD

**Issue by Quagel** [dennrick/LineageRoleplay#113]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    On disconnect and reconnect the character's outfit will not always be what was worn last. I believe this is currently defaulting to the last time the player hit 'Save Changes' at a clothing store and it does not apply to the use of /outfits or outfit racks/closet. Headpops can be especially tricky for RP situations sometimes pulling the character out completely if logging in back with Crim/Non-crim outfits.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Put on new clothes at clothing store. Click 'Save Changes'.
    2. Change to a previously saved outfit.
    3. Disconnect and Reconnect
    4. Should appear in outfit from step 1.

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    After selecting an outfit from /outfits, changes should save to the characters default/log-in outfit.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
@MjrDeathAdder can you take a look at this with your other changes to the outfit system?
