### ISSUE TITLE
Unable to Lay Spikestrips 

### ISSUE THREAD

**Issue by XxN1TRODR1FTXx** [dennrick/LineageRoleplay#114]
## [BUG REPORT] I was trying to help commander wrath in a persuit when i thought now would be a good time to lay spikestrips im able to lay a tent but unable to lay spikestrips. Only just found this big 05/30/2021 Time roughlt 7:05 on VOD 

**Describe the bug** *(A clear and detailed description of what the bug is):* Unable to lay down spikestrips in the road.

    Describe bug here...

**To Reproduce** *(Steps to reproduce the behavior):*
  

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Expected behavior details here...

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    https://www.twitch.tv/videos/1040434076 about 19:05 PST
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

![20210530191725_1](https://user-images.githubusercontent.com/84733238/120116002-eca15180-c17d-11eb-815b-a3338fee415f.jpg)
wouldnt let me lay down spikes as said above maybe just a minorissue what needs fixing. :)

**Comment by dennrick** [comment]
Fix applied to PTR - keep an eye on DevUpdates in Discord for when it is pushed live

**Comment by XxN1TRODR1FTXx** [comment]
Thank you :)
