### ISSUE TITLE
[BUG] Always On-Call

### ISSUE THREAD

**Issue by PerfectLies86** [dennrick/LineageRoleplay#115]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

While off-duty as EMS (likely PD as well) you will get calls to Dispatch.

This bug is nice for Mechanics as some of us do go on duty to help out while off shift.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Go into the city
    2. Go off shift if you aren't already
    3. Wait for someone to go down
    4. See dispatch pop up

**Expected behavior** *(A clear and concise description of what you expected to happen):*

   While off shift do not receive calls from Dispatch for EMS & PD.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
   N/A

**Additional context** *(Add any other context about the problem here):*
    
    N/A
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    N/A

**Comment by dennrick** [comment]
Waiting on a fix for this from codesign which they have patched.
