### ISSUE TITLE
[BUG] Rental App Vehicle Spawns at Prison Every time

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#116]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

> Rental vehicles spawn at prison not nearest location.

**To Reproduce** *(Steps to reproduce the behavior):*
  
> go to a rental location
spawn vehicle through app
vehicle spawns at prison

**Expected behavior** *(A clear and concise description of what you expected to happen):*

> spawn to nearest rental location

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
![image](https://user-images.githubusercontent.com/82202019/120339599-19eb1e00-c2aa-11eb-93ab-00141dc52eb4.png)

**Comment by dennrick** [comment]
Instead of fixing this exactly I want to build out a system as follows:

1.  Pay for Rentals by the hour
2. If near certain locations (other secret planned feature) then rental is only for x amount of time for those vehicles
3. Can either be in phone or standalone
