### ISSUE TITLE
[BUG] Super glue in apartment stash

### ISSUE THREAD

**Issue by overlordrockz** [dennrick/LineageRoleplay#118]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    I am unable to take anything out of my apartment stash no matter what i type in the amount part. I have not been able to take anything out of my apartment since last night (5/31/21)

**To Reproduce** *(Steps to reproduce the behavior):*
  

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Expected behavior details here...

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
@overlordrockz please file a Help Me ticket on this as we will need more info.  Closing this one out.
