### ISSUE TITLE
[FEATURE] Agency for my PI/Detective 

### ISSUE THREAD

**Issue by xMACxMRJOKA** [dennrick/LineageRoleplay#12]
I think being able to have a agency in the city where people come to get private cases done. I work with anyone to help solve murders, gang violence and even drug trafficking. This would be a great feature for the city as my character is a great PI. I can also look for location and provide a good spot to work on.

**Comment by daddyDUBZ** [comment]
This request would best be served in the form of an SOP request.  You should write and submit a request to operate such a business including how the business would function, and any special permissions characters would need including buildings to operate from vehicles required etc.  Be as detailed as possible with this submission.

**Comment by daddyDUBZ** [comment]
At this time we are going to close this ticket.  At such time that you write an SOP for your request please complete the corresponding ticket and include the requested details.  SOP submissions are requested in Word365 or GoogleDocs formats.

Thanks,

daddyDUBZ
Lineage Support
