### ISSUE TITLE
[BUG] Joint Issues - Stress/Animation

### ISSUE THREAD

**Issue by Quagel** [dennrick/LineageRoleplay#120]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    A few issues when using joints: Joints display a message stating that they will relieve stress but however when using them they do not and only apply extra armor. Joints also do not display any smoke/light animation (lighter does not appear to do anything). When using a joint in car the cigarette emote is displayed.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Gain stress and mark/note level. 
    2. Smoke joint.

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Smoking joints should cause stress to decrease.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
Fix applied to PTR for armor/stress issues - Animation limited do to the one I want not being available for females.  Will have to leave it as is for now until I find something else.
