### ISSUE TITLE
[BUG] Lockpicking & Losing Keys

### ISSUE THREAD

**Issue by Quagel** [dennrick/LineageRoleplay#122]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    If you receive keys while lockpicking a vehicle and you will lose the keys if you fail the attempt. This can happen in two scenarios: 1) Player hands/givekeys you the keys when performing a lockpick. 2) There seems to be chance when entering a ped parked vehicle that the car will be able to start/keys were left in it (unsure if bug or intented, keys left in vehicle). This seems to follow the standard GTA picking and the start-up and is on a delay allowing you to lockpick prior to the vehicle starting.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1.1) Start lockpick
    1.2) Have second player give keys during pick
    1.3) Fail the lockpick
    2.1) Break into ped cars and start lockpick immediately
    2.2) On chance you will start car during lockpick.
    2.3) Fail lockpick

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    When failing a lockpick if you already have keys to the car they should not be removed.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
I'm pretty sure this is working as intended.  You shouldn't be able to lockpick a vehicle that you have keys for.  So by having someone give you keys after you start lockpicking then the game still thinks you don't have them and therefore removes them when lockpicking is failed.

@MjrDeathAdder can you give your opinion here?

**Comment by MjrDeathAdder** [comment]
I mean this isn't really issue enough to patch. Just dont lockpit your friends car.
