### ISSUE TITLE
Black Woods Saloon and Distillery

### ISSUE THREAD

**Issue by HunterR26** [dennrick/LineageRoleplay#123]
## [SOP Request]    

**General description of your SOP request:**
Black woods Bar is a family owned bar and distillery. This is the current premier location for local restaurants and bars with Liquor Licenses in the city to purchase their alcohol.
    

**Would people work/affiliate with this SOP?**

    Yes, No, and how many? No

**What permissions, scripts, interiors, special vehicles etc. are required?**

    Black woods Bar that is in Paleto. Possibility of having a still in the general area 

**SOP Request**

    Complete your SOP request in a Google/Office365 document format and include a link to the document here

https://docs.google.com/document/d/1gi9lD64JG-yvOA8CJRXdtR0mtFnA725spcQIYYA-Biw/edit?usp=sharing

**Comment by HunterR26** [comment]
Drink menu and Food menu will be updated.

**Comment by dennrick** [comment]
OPened in Discord will continue this there
