### ISSUE TITLE
[BUG] Non-stackable Items from Burgershot

### ISSUE THREAD

**Issue by Quagel** [dennrick/LineageRoleplay#124]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    Once split some items from the burgershot (listed below) no longer can be stacked. Tested all items sold at burgershot
    Fries, Chicken Nuggets, Spurnk, Ecola, Diet Ecola, Orange-o-tang

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Go to burgershot purchase multiple of same item from above and try to unstack/stack in inventory.

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Items should be able to unstack and restack back together freeing/cleaning up player inventory space

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
Confirmed bug

Patched in PTR - Keep an eye on DevUpdates in Discord for when this fix goes live
