### ISSUE TITLE
[BUG] DRUGS NOT GIVING EMAIL FOR DELIVERY LOCATION

### ISSUE THREAD

**Issue by DoctorDirtyDave** [dennrick/LineageRoleplay#125]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    Describe bug here... you get the drugs from the postal 567 but it give you the assignment but doesnt give you a location. 

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Go to 'Go Postal 567 at the Up N Atom place and go up the drive thru
    2. Click on 'Flex E muscle then G muscle for the assignment then check email

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Expected behavior details here...

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...
![Drugs](https://user-images.githubusercontent.com/85419044/120907830-704db900-c62a-11eb-921e-9b84a92c6473.PNG)

**Comment by dennrick** [comment]
Unable to replicate

**Comment by swintell** [comment]
Happened to me last night. Same error.

**Comment by GradientWizzard** [comment]
Either tomorrow or Monday for a fix
