### ISSUE TITLE
[BUG] Accessing other inventories

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#127]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

> Accessing another players inventory when looking into my apartments stash. Left side should be MY PERSONAL inventory and actually was Officer Bishops. This happened at approximately 6:17 EST

**To Reproduce** *(Steps to reproduce the behavior):*
  
> -Spawn in
-Access STASH
-Back out
-Immediately access again

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Expected behavior details here...

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
5:13 PM] kraKen: @AllyCatt237 what can we help with?
[5:13 PM] AllyCatt237: Im going to submit a ticket about the player inventory. I opened this prematurely, and I am not ready to submit. Can we keep this open and I'll submit once I have the info
[5:14 PM] kraKen: sounds good
[6:57 PM] AllyCatt237: Describe the bug
Accessing another players inventory when looking into my apartments stash. Left side should be MY PERSONAL inventory and actually was Officer Bishops. This happened at approximately 6:17 EST
What steps should we take to reproduce the issue?
-Spawn in
-Access STASH
-Back out
-Immediately access again

That is what I did.

Expected behavior
I think thats an obvious answer. I should have been able to access mt own not someone elses.
[6:58 PM] AllyCatt237:
![image](https://user-images.githubusercontent.com/82202019/121260417-2bae6180-c866-11eb-9287-38d1c87e18aa.png)

[6:58 PM] AllyCatt237:
![image](https://user-images.githubusercontent.com/82202019/121260427-2f41e880-c866-11eb-9ed1-44eec12d2ae7.png)

[6:58 PM] AllyCatt237:
![image](https://user-images.githubusercontent.com/82202019/121260435-31a44280-c866-11eb-89d8-a593872f2f7e.png)

[2:12 PM] Dennrick: We are investigating this issue.  Can this be escalated to github @Technical Support
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by swintell** [comment]
I have experienced this tonight I took a 
![20210630204515_1](https://user-images.githubusercontent.com/82983334/124067039-4dcb7780-d9ff-11eb-8099-7f3b5b4f18e0.jpg)
screenshot it before closing the inventory.

This was not my inventory It was right after someone handed me something, dont know if that has ANY thing to do with it.
