### ISSUE TITLE
[PLAYER REQUEST] Player Name Change

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#129]
## [Player Request]

> Player Current Name: Audrey Lipper
Player New Name: Audrey Static
Player ID: DYL46602

**Additional context**

> Wayne Static and Audrey Lipper were married on 06/05/2021

[waynenaudreycertificate.pdf](https://github.com/dennrick/LineageRoleplay/files/6620845/waynenaudreycertificate.pdf)

**Comment by MjrDeathAdder** [comment]
Completed
