### ISSUE TITLE
[BUG] Radio in Boiling Broke

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#13]
# [BUG REPORT]

## Describe the bug *(A clear and detailed description of what the bug is)*
**Radio remains connected when transferred for prison sentence.**
## To Reproduce *(Steps to reproduce the behavior):*
**Join a radio station and go to prison**
## Expected behavior *(A clear and concise description of what you expected to happen):*
**Disconnect from any connected stations**
## Screenshots *(If applicable, add screenshots to help explain your problem):*
**None available**
## Video Clip of the Issue Happening *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
**None available**
## Additional context *(any other context about the problem):*
**None available**

**Comment by MjrDeathAdder** [comment]
Requires testing
