### ISSUE TITLE
Burgershot Looses texture loss when you are looking through eyes 

### ISSUE THREAD

**Issue by XxN1TRODR1FTXx** [dennrick/LineageRoleplay#130]
## [BUG REPORT] so on my visit to burgershot i was looking around as i noticed it changed as soon as i looked through my eyes in the back area where the box of chicken was i lost alot of texture as i will attach photos to proove my experience when visiting burgershot 

**Describe the bug** *(A clear and detailed description of what the bug is):* loose alot of texture when looking through your eyes espcially in the back area 

   soon as you walk into the back area and press v You will loose alot of texture i dont know if its just me or if this happens to anybody else 

**Expected behavior** *(A clear and concise description of what you expected to happen):* i know you devolpers are extremely busy and when you get chance to look at this i dont exspect it to be done the same day as the ticket went in ill just keep an eye out on devolpment updates.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):* 1:08 timestamp, of the vod 06/10/2021 
    
https://www.twitch.tv/videos/1051710265

 
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

![back room when looking through eyes](https://user-images.githubusercontent.com/84733238/121520023-50cbdd00-c9ea-11eb-9c78-5ccd4fab1ced.PNG)
![not looking through eyes](https://user-images.githubusercontent.com/84733238/121520031-53c6cd80-c9ea-11eb-8455-e5a05b49b000.PNG)
![back room when looking through eyes](https://user-images.githubusercontent.com/84733238/121520046-588b8180-c9ea-11eb-8e5e-f5e71e8d99de.PNG)

**Comment by XxN1TRODR1FTXx** [comment]
![Uploading tiolet when looking through eyes.PNG…]()

**Comment by XxN1TRODR1FTXx** [comment]
![tiolet when looking through eyes](https://user-images.githubusercontent.com/84733238/121608356-ae434680-ca49-11eb-9110-81c02e57bacc.PNG)

**Comment by HUNT3RxLG** [comment]
I have just been and had a look at this in the PTR dude and for me it is all fine i will check the live server later today

**Comment by XxN1TRODR1FTXx** [comment]
Its in the live server it happens myguy!! In the back area 😊 where the toilets are

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by HUNT3RxLG** [comment]
Ya buddy i just checked in the live server and it is all fine for me

**Comment by dennrick** [comment]
This appears to be happening only to a few players. We do have plans to swap this interior again in the future when a new version comes out. Probably not going to mess with this until then.
