### ISSUE TITLE
[BUG] Items Disappearing From Stash

### ISSUE THREAD

**Issue by Quagel** [dennrick/LineageRoleplay#134]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    I have a had a few items now that have disappeared from my stash. So far, from what I have noticed, I have had a stack of iron (2k+) and some joints (50+) disappear.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    Unsure of steps to reproduce. Most recently lost the joints, which I noticed today. I had put ~5 new joints into my stash yesterday evening, ~24hrs.

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Expected behavior details here...

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by MjrDeathAdder** [comment]
I need your CitizenID number please

**Comment by Quagel** [comment]
Is that the number on the login? If so, YTB97140
