### ISSUE TITLE
[BUG] gas can flight

### ISSUE THREAD

**Issue by overlordrockz** [dennrick/LineageRoleplay#135]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    If you use a gas can from ammunation you will be forced to take a flight.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Go to ammunation
    2. Buy a gas can
    3. Equip and use the gas can

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Expected behavior details here...

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
We are aware of this issue and a patch is being applied to PTR and should be included in one of the next updates to hit the server.

**Comment by dennrick** [comment]
Should also be resolved with the newest updates fixing fire extinguishers
