### ISSUE TITLE
Mechanics on Page Up Menu

### ISSUE THREAD

**Issue by Kaos131** [dennrick/LineageRoleplay#136]
## [Feature Request]

**Is your feature request related to a problem?** *If so, describe in detail:*

  No

**Describe the solution you'd like to see:**

   Showing the mechanics on the Page Up menu when they are on duty, similar to both PD & EMS.

**Describe alternatives you've considered:**

    N/A

**Additional context**

    Add any details or screenshots or video recordings (including timestamps) that provide additional context

**Comment by dennrick** [comment]
Done - added at 4am Update on 6/30
