### ISSUE TITLE
[BUG] motorcycles randomly exploding

### ISSUE THREAD

**Issue by swintell** [dennrick/LineageRoleplay#138]
## [BUG REPORT]

**Describe the bug** *numerous counts of motorcycles randomly smoking for no reason (no damage taken) also sometimes they just randomly catch fire and explode after getting off of them:*

    Describe bug here...

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Get a motorcycle
    2. Drive it around a bit
    3. Hope your not one of the lucky few
    4. Motorcycle will smoke, catch fire and combust

**Expected behavior**

    Expected vehicles across the board to be far more sensitive with the new damage system, however currently motorcycles are undriveable at the moment. I spoke to about 14 or 15 people today who own motorcycles and it was all the same story not matter the bike style.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    It should also be noted that some bikes are being pulled out of the garage with a fuel leak even after being repaired.  This has happened to 2 people that I know of and the mechanics are baffled by it. Primarily happening to the hexer. This damage sensitivity has also effected the place runs and made the whole job nearly impossible  
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
Is this still happening since we scaled back the damage system, @swintell ?

**Comment by swintell** [comment]
Negative. It seems to be fully fixed. I can assure you the ENTIRE CLUB THANKS YALL. Lol

**Comment by dennrick** [comment]
Perfect Closing this out
