### ISSUE TITLE
[BUG] clear your throat! Your mumbling!

### ISSUE THREAD

**Issue by swintell** [dennrick/LineageRoleplay#139]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    I realize this is a known issue with mumble but you guys always want us to submit tickets anyways just in case. It is a city wide issue thag mumble just quits working quite often. Like 4 or 5 times within a 2 minute time span. The solution is to turn off then back on your in game voice chat settings. 

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Fly into city
    2. Walk up to someone
    3. Have conversation 
    4. Develope awkward silence and realize one of you can't be heard. Cycle voice and your back in business.

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Known issue I've seen before just a lot less frequently in such short periods of time.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
Closing as the plan is to migrate back to teamspeak
