### ISSUE TITLE
[BUG] fire extinguisher error crash

### ISSUE THREAD

**Issue by swintell** [dennrick/LineageRoleplay#140]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    Fire extinguishers cause whoever is firing it to crash after about 2 seconds of using it. Not sure if this bug has been submitted but we found it once when playing with some thermite and tested it across 4 players. Then forgot to submit the ticket then today it happened to an officer while trying to put out a bike fire.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Buy extinguisher
    2. Pull pin, aim, squeeze the trigger, sweep side to side
    3. Wait 2 seconds
    4. crash your game

**Expected behavior** *(A clear and concise description of what you expected to happen):*

   To not crash your game while trying to save lives. Or harass friends with toxic chemicals

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
This has been patched on PTR and will be pushed live to the server at 4am EDT on 7/4
