### ISSUE TITLE
[BUG] Vehicles not storing upgrades/cosmetics

### ISSUE THREAD

**Issue by dennrick** [dennrick/LineageRoleplay#142]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    Certain vehicles are not saving cosmetics and/or upgrades.  

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Spend money on cosmetics or upgrades
    2. Store vehicle
    3. Pull out of garage
    4. No upgrades or cosmetics changed

**Expected behavior** *(A clear and concise description of what you expected to happen):*

   Upgrades and cosmetics should be saved to database and restore on pull from garage.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    N/A

**Additional context** *(Add any other context about the problem here):*
    
    N/A
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    N/A

**ANY VEHICLE WITH THESE ISSUES SHOULD BE REPORTED UNDER THIS TICKET WITH AS MUCH DETAIL AS POSSIBLE**

**Comment by dennrick** [comment]
Tubby — 06/20/2021
On the massacro everytime you change the wheels and put it in the garage it changes them to a different random wheel
(Sports Car)

**Comment by dennrick** [comment]
JsMo0f — 06/29/2021
audi  upgrades dont stick

**Comment by dennrick** [comment]
NoDoughNoGo — 06/30/2021
Livery on BMW M3 continues to show up when car is pulled from garage even after removing the livery at the Mechanic's shop. Others have had the same issue. I have not tried any other upgrades or cosmetic changes to see if those are sticking.

**Comment by dennrick** [comment]
![image](https://user-images.githubusercontent.com/46427576/125989917-d792f6f2-5c08-4cc0-af21-ec4c9c16c866.png)

**Comment by dennrick** [comment]
> JsMo0f — 06/29/2021
> audi upgrades dont stick

Also reported by Cheezy

**Comment by daddyDUBZ** [comment]
HunterR26 Bugatti mods do not save
