### ISSUE TITLE
[BUG] Able to Access Others Inventory when Hitting F2

### ISSUE THREAD

**Issue by dennrick** [dennrick/LineageRoleplay#143]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    In some instances when you access your inventory it is pulling the inventory of another player.

**To Reproduce** *(Steps to reproduce the behavior):*
  
1.  Hit F2 and see if it be your inventory or the inventory of another

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    You should only be able to access your inventory or stash.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    N/A

**Additional context** *(Add any other context about the problem here):*
    
    N/A
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    [image](https://user-images.githubusercontent.com/46427576/124367705-c3199100-dc27-11eb-9f7b-e7191391e732.png)

**Comment by swintell** [comment]
are you wanting F8 screen shots or any more screen shots of this bug? everytime it happens i shoot it.

**Comment by dennrick** [comment]
Will be resolved in https://github.com/dennrick/lineage/pull/49
