### ISSUE TITLE
[BUG] ammo disapearing out of weapons found in dumpsters

### ISSUE THREAD

**Issue by swintell** [dennrick/LineageRoleplay#145]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    All weapons found in dumpsters have a bug where you will load them with ammo then after a bit the ammo will disappear. 

**To Reproduce** *(Steps to reproduce the behavior):*
  

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Ammo to stay in the guns

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by swintell** [comment]
I wanted to add to this that the smg and mk2 pistol you get from dumpsters will not take attachments

**Comment by XuranuTV** [comment]
This bug is also true of PD Pistols, PD SMGS, and PD Assault Rifles. Ammo is not currently staying in the gun....
