### ISSUE TITLE
2 PageUp Potential Addons

### ISSUE THREAD

**Issue by JoeSBraddock** [dennrick/LineageRoleplay#146]
Shootings & Pursuits

There been two occasions where only 4 cops have been on just enough to do a jewelry store and a shooting has taken place, and 4 cops are not enough to handle a shooting situation properly.

Pursuits should be tied to same number as Jewelry Store and Fleeca Bank robbery just so there will always be at least 4-5 cops on at any time for a pursuit to take place, I've been in a couple situations where I ended up the only officer on and I'd respond to a robbery and multiple other ones pop off and I get held up because the person I'm currently on a robbery scene of is trying to take up the only officer for a pursuit.

Shooting being connected to same amount of officers as Pacific Standard Bank will ensure their are plentiful number of officers to respond to a shot fired call. Or set it to 8-10 officers only just so there back up available.

Pursuits being tied to Jewelry Store means there has to be 4 officers on at least, so when 3 officers max on a pursuit there still at least one roaming around the state.

This will help keep cops from getting overwhelmed and frustrated in almost all situations of these taking place that would cause officers to just go back to station and clock off.

**Comment by dennrick** [comment]
These have been discussed and we decided not to implement these requirements for now.
