### ISSUE TITLE
[BUG] Apartment Logout

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#15]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    Logout at bed does not operate as expected

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Go to the bed in apartment
    2. Logout using instructed keypress
    3. Check F8 for errors *Screenshots attached*

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    The expected behavior of the bed logout function is to lose any assigned character permissions, disconnect from any 
    connected radio stations, and return to character selection.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Not available
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*

    See below...

![image](https://user-images.githubusercontent.com/82202019/115161933-3f52fe00-a055-11eb-988d-7e62e3297255.png)

![image](https://user-images.githubusercontent.com/82202019/115161941-509c0a80-a055-11eb-9a29-cd6b88c3ad7a.png)

**Comment by dennrick** [comment]
I've applied a fix for this in the test server.  Moving to in-progress.
