### ISSUE TITLE
[/admit] Basically a similar script police use to jail someone, instead they are sent to private room in hospital for X amount of time.

### ISSUE THREAD

**Issue by JoeSBraddock** [dennrick/LineageRoleplay#151]
I had a few people who like that idea and figured it was worth throwing in a feature request.

Basically depending on severity of the injury "/admit [time] [injury]" could be done which would send patient into one of the private rooms, they would be able to wonder through hallway and their room, but the main doors/elevators from the private rooms would be locked until their time was over.

It'd allow anyone involved in fire, explosion, severe height fall, etc. Just any major injuries to sustain an extended hospital stay for health care.

**Comment by dennrick** [comment]
Will need to have some discussion with staff on this.
