### ISSUE TITLE
[Traction Reduction Tires] Not sure how long after GTA Online update drops we can potenially get files in FiveM

### ISSUE THREAD

**Issue by JoeSBraddock** [dennrick/LineageRoleplay#152]
GTA Online Tuner update gave some nice vehicles which would be nice, but not the point of this feature request.

There is a new modification to Tire Enhancement that can be put on any car that reduce traction which allow more than specific vehicle models to have a drift mode which would be nice. And when you wanted to not have drift mode you just go back to mechanic and swap them back out.

**Comment by dennrick** [comment]
This is something that we would need to wait for FiveM to update the build for as we can no longer pull items, cars, etc from later game builds than what we are running in the server.  I'm unsure at the present moment how this would impact the scripts we run for handling and all that.  This may just be something we need to look at implementing other ways.
