### ISSUE TITLE
Police Taser is not Functioning Properly

### ISSUE THREAD

**Issue by Retired1SGDW** [dennrick/LineageRoleplay#156]
When you get the Taser out from the Armory and aim it, there is no Green Charge in the Upper Right Hand Corner. I tried multiple things to get it to work. Some people do not have issues taking the taser out and works properly. If that same taser is give to another who has problems with it sometimes it will work. I have went into the PTR with Accidont and ensured it is not working.

**Comment by dennrick** [comment]
Hey @Retired1SGDW when did you go into PTR and test this?

**Comment by Retired1SGDW** [comment]
Yes Sir me and Accidont tested this yesterday
    On Wednesday, August 11, 2021, 12:25:57 PM CDT, Dennrick ***@***.***> wrote:  
 
 


Hey @Retired1SGDW when did you go into PTR and test this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dennrick** [comment]
Fixed https://github.com/dennrick/lineage/pull/49
