### ISSUE TITLE
[BUG] Rented a vehicle, it came with ~10% gas?

### ISSUE THREAD

**Issue by T3rminat0r** [dennrick/LineageRoleplay#157]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

  I rented a Panto from Integrity Way, and drove towards the Golf Course. I did not make it 4 Blocks, before the low gas warning sounded and then the car actually ran out of gas a minute later.

**To Reproduce** *(Steps to reproduce the behavior):*
  (not sure how reproducible it is ... Car's Plate Was Rent5000)
    1. Go to Integrity Way Rental
    2. Rent a Panto
    3. Check the Gas Meter
    4. Drive <5 Minutes and note the Car is out of Gas

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    I'd expect to get a full tank of gas, as I did all the other times I did rent a car there.

**Additional context** *(Add any other context about the problem here):*
    
    My Discord User is Trminator85 / Mike Schmidt (T3rminat0r#0218)

**Comment by T3rminat0r** [comment]
I did not notice anything like that, anyways, but I was in a hurry, so ... possible, albeit unlikely, I drove it down those stairs as always...

**Comment by dennrick** [comment]
Fixed with 4035a60
