### ISSUE TITLE
[BUG] Effects of specialized food items/weed on females

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#16]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    Drugs do not work effectively on females.  Food from BurgerShot adds stress

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Walk like a woman
    2. Talk like a woman
    3. Do some drugs or eat some burgershot

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Smoking joints should give armor and eating burger shot should not add stress

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your problem):*
    
    Not available

**Additional context** *(Add any other context about the problem here):*
    
    THIS IS WITH REGARD TO FEMALE CHARACTERS
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Not Available

**Comment by dennrick** [comment]
Joint issue fixed with a workaround causing all players to have to manually end animation.

What food items was adding stress from burgershot?

**Comment by daddyDUBZ** [comment]
AffintyRose reported stress induced by eating fries and nuggets, but has not been back since.
