### ISSUE TITLE
[BUG] MISSING CAMERAS/ROBBERIES

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#17]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

>THIS TICKET IS OPEN STILL WITH REGARD TO OPENING OF DONS COUNTRY STORE IN PALETO BAY

    [4:58 AM] [O-46] Valdor: I was going through the PD Cameras to attempt to learn where each camera specifically was.  When
     cross checking the cameras with the map I discovered 3 locations that do not have cams.  The Grapeseed 24/7 (postal 2013),
     Palamino Freeway 24/7(postal 402), and the Route 68 Fleeca Bank(postal 940) do not appear to have cameras set up.  I
     checked all of them up  to 34 (Vangelico) then also confirmed that 35-40 "do not exist" just in case the numbering was off.
    [5:25 AM] MjrDeathAdder: Im pretty sure they exist. I haven't had a a robbery without being provided a valid camera option.
     Will keep this open for monitoring
    [5:41 AM] [O-46] Valdor: I was able to compile a full list of each camera 1-34 and its location with postals
    [6:04 AM] [O-46] Valdor: Additional Note: Cameras 28,29, and 30 are for "Don's Country Store" in Paleto Bay, which seemingly
    does not have a map to it (one of the cameras does show a "shop arrow" but we are unable to otherwise enter the location, 
    and it is marked on the map as a convenience store.

> 6:28 PM] Dennrick: Grapeseed camera added - check #dev-updates this weekend for more info
> Palomino at 402 doesn't have a robbery
> Fleeca on 68 doesn't have a robbery
> Don's will be open soon - keep an eye on #dev-updates for more info

    Keeping ticket open for tracking

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Dons Country Store Paleto Bay Not open No robbery
    2. 
    3. 
    4. 

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Expected behavior details here...

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
Resolved
