### ISSUE TITLE
[BUG] NVE/City Hall Compatability 

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#20]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    Unable to enter city hall when using NVE/ENB reported by Xuranu

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Install most recent NVE/ENB
    2. Attempt to enter city hall
    3. 
    4. 

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Be able to enter city hall while running NVE

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
https://drive.google.com/drive/folders/1disFiEpk0ysd53q6YXT-2YQtPhd6gO22?usp=sharing

**Additional context** *(Add any other context about the problem here):*
    
    Reporter's understanding is updated city hall was removed due to similar issue.  Issue is ongoing after downgrading to
    previous interior
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    See video clip

**Comment by dennrick** [comment]
Is the custom street lights addon being ran on NVE?

**Comment by daddyDUBZ** [comment]
Xuranu confirmed this was with NVE completely removed

**Comment by daddyDUBZ** [comment]
Cute I had tested this with the latest nve release and appears to be resolved

**Comment by dennrick** [comment]
Going to close this out as NVE itself is out of our control.
