### ISSUE TITLE
[SOP] Salvage and Scrap Business

### ISSUE THREAD

**Issue by swintell** [dennrick/LineageRoleplay#21]
## [SOP Request]

**General description of your SOP request:**

    Seeking to open a whitelisted version of the salvage and scrapyard to offset the grind of citizens not wishing to collect materials themselves. Operate in an official and trusted capacity so that others may utilize the source to possibly form other roleplay businesses as well as other scrap related activities. I believe having an official, consistant source of scrap materials could open the door to a lucrative stable economy throughout the city while providing many opportunities for many different types of roleplay through it.

**Would people work/affiliate with this SOP?**

    Yes, the company structure is explained in the Google doc sop. Owners, foremans and technicians. The Foreman would act as a crew boss and the technicians would act as the crew. Their job duties are also listed. 

**What permissions, scripts, interiors, special vehicles etc. are required?**

    These are also all listed within the Google doc. 
A new mechanic system is sourced inside the document to provide better more realistic roleplay using materials to fix vehicles. This would also open the door to other ideas people may not know they have yet involving other businesses using scrap materials to create a good and/or service.

**SOP Request**

    https://docs.google.com/document/d/1js_42JJxTEyxwEY532GfWkHE3IXy4V1tODvbF0t4hbA/edit?usp=drivesdk

**Comment by dennrick** [comment]
Closing this as it is also on Discord
