### ISSUE TITLE
[BUG] buying from multiple dealers

### ISSUE THREAD

**Issue by swintell** [dennrick/LineageRoleplay#26]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    After purchasing from a dealer, you are unable to purchase from a different dealer until the next storm. Didnt know if this was intentional or a bug.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Go to dealer A buy bags
    2. Go to dealer B right after to buy bags
    3. Allows you to purchase says takes money
    4. Money doesn't come out of pocket,  and no bags produced

**Expected behavior** *(A clear and concise description of what you expected to happen):*

   To possibly be able to buy from multiple dealers?

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    None

**Additional context** *(Add any other context about the problem here):*
    
    None
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
   None

**Comment by MjrDeathAdder** [comment]
This issue has been addressed but I'll leave this here for tracking reasons. Thanks for the bug report :)
Keep an eye on the devlog updates in the near future, this ticket will be closed out when the time comes also.
