### ISSUE TITLE
[SOP] Official Formation of GGMC

### ISSUE THREAD

**Issue by swintell** [dennrick/LineageRoleplay#27]
## [SOP Request]

**General description of your SOP request:**

    The GGMC is a group of friends who enjoy MC roleplay. We were formed in 2020 and wish to return to fivem, we have since landed in lineage as our home having loved the community here. 

**Would people work/affiliate with this SOP?**

    There are four whitelisted members already with 3 more applying 

**What permissions, scripts, interiors, special vehicles etc. are required?**

    We have always posted up at the lost club house in mirror park. The MLO that is already in place is the one we have had in the past.

**SOP Request**

https://docs.google.com/document/d/1Xj69B14oeFiV2UZSW0cB0QDVSrfu62eunLg2wX57m8I/edit?usp=drivesdk

**Comment by dennrick** [comment]
closing - in discord already
