### ISSUE TITLE
[BUG] Grocery Store Safe Note NIL Value

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#29]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

> [6:57 PM] Fithesis: Reporting this bug at the grocery store
> [6:57 PM] Fithesis: Location is 2013
> [6:57 PM] Fithesis: It always gives you a nil note
> [6:58 PM] Fithesis: This is the 5th time I've got this
> [6:58 PM] Fithesis: Never has it once given me a ligit code
> [7:34 PM] kraKen: @daddyDUBZ this can go to the github

**To Reproduce** *(Steps to reproduce the behavior):*
  

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Receive code on note in place of NIL value

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    
![image](https://user-images.githubusercontent.com/82202019/116177390-934e8a00-a6c8-11eb-993f-7e03ce30ce16.png)

**Comment by overlordrockz** [comment]
I've gotten that 2 times at the store on grove street before as well. It seems to more commonly happen the first time a store is hit after a storm from what I've seen.

**Comment by MjrDeathAdder** [comment]
Are there any known F8 Script errors associated with this?

**Comment by dennrick** [comment]
Fix Applied in test server for postal 2013 (Grapeseed) store.  Will need to tested to see if this also resolves @overlordrockz reported issue at Grove.
