### ISSUE TITLE
[FEATURE] VENDOR-Pier Bait and Tackle shop

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#3]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Add a bait and tackle vendor postal 612. 'Master Baiter Bait & Tackle' Near Pearls  ***see screenshots*** 

**Describe alternatives you've considered**
Bait and tackle at one of the stands on the pier

**Additional context**
![FiveM_b2060_GTAProcess_fxyE7whO66](https://user-images.githubusercontent.com/82202019/114320642-b7587b80-9acb-11eb-9ce6-47bcf9e84954.jpg)
![FiveM_b2060_GTAProcess_OcmqTsrvyH](https://user-images.githubusercontent.com/82202019/114320646-be7f8980-9acb-11eb-9453-982d411fbdae.jpg)

**Comment by dennrick** [comment]
Implemented in PTR
