### ISSUE TITLE
[SOP] Lineage Repairs #Fasha

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#30]
## [SOP Request]

**General description of your SOP request:**

    None given

**Would people work/affiliate with this SOP?**

    None given

**What permissions, scripts, interiors, special vehicles etc. are required?**

    None given

**SOP Request**

    [Lineage_Repairs_ (1).pdf](https://github.com/dennrick/LineageRoleplay/files/6381525/Lineage_Repairs_.1.pdf)

**Comment by dennrick** [comment]
Closing - handling in discord
