### ISSUE TITLE
[DEV-REQUEST] Character name change

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#31]
## [DEV-REQUEST]

> [10:16 AM] AndyMcFly: i named my Karen with an E, but she's supposed to have a "I" (Karin) and i had made her quickly during that initial week of 2.0 launch, and ive been playing her but didnt realize id made the typo til i had to show my license to a cop and i was like, oops! The character ID is YFP44047 right now it's Karen Shrieker, should be Karin Shrieker

**Comment by dennrick** [comment]
Done
