### ISSUE TITLE
[BUG] BANK ACCOUNT NEGATIVE BALANCE

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#33]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

>  5:15 PM] LilClown: App basically over the course of 2 days I went to the mechanic and purchased upgrades, they never over charged me because I double checked my accounts and I had plenty of cash, however I would still some how end up in the negative?? I’m just curious if it might be a bug or if there is something I’m doing on my end

**To Reproduce** *(Steps to reproduce the behavior):*
  

**Expected behavior** *(A clear and concise description of what you expected to happen):*

> Balance is expected

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    

**Additional context** *(Add any other context about the problem here):*
    

    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*

**Comment by dennrick** [comment]
Need more details.  Citizen ID of player is required on this.

**Comment by MjrDeathAdder** [comment]
Confirmed. Bank balanced has been allowed to go negative in the code by design. If this isn't meant to happen a small change in thr configs will resolve

**Comment by MjrDeathAdder** [comment]
Forced non negative bank balances
