### ISSUE TITLE
[BUG] APARTMENT STASH/CLOSET ACCESS 

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#34]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

> It is possible to open both the stash and closet in an apartment if you do so while moving past the stash.  If this happens you become stuck until disconnect form server.

**To Reproduce** *(Steps to reproduce the behavior):*
  
>1. Run past stash to closet
>  2. Click E on closet as soon as it becomes available
> 3. There is a point where both items become selectable simultaneously 
> 4. See error

**Expected behavior** *(A clear and concise description of what you expected to happen):*

> Only be able to open one or the other.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
  
> NA  
  
**Additional context** *(Add any other context about the problem here):*
    
> NA
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
> NA

**Comment by dennrick** [comment]
Solution is to not be in a rush to click on things in the server.

This should be remedied when we roll out the new apartment shell(s).

**Comment by dennrick** [comment]
Closing for now
