### ISSUE TITLE
[FEATURE] Seating in High traffic RP areas

### ISSUE THREAD

**Issue by overlordrockz** [dennrick/LineageRoleplay#36]
## [Feature Request]

**Is your feature request related to a problem?** *If so, describe in detail:*

    no it's not related to a problem, but it would enhance the rp immersion. I would like to see the ability to sit in the chairs that are positioned at desks that are in some interiors around the city. For example, if someone is reporting a crime at MRPD an officer could take them back to the desks  and both individuals could sit down to get the paperwork filled out. Or, if someone comes in for an interview for a whitelisted job both parties could sit down one behind a desk and the other on the opposite side of the desk.

**Describe the solution you'd like to see:**

    Ideally, I'd like to see something similar to how the beds in pillbox  work; you walk up to the chair, a little notice pops up above it that says something like "Press [E] to sit" 

**Describe alternatives you've considered:**

    Alternatively, the chairs could be moved out a little and/or rotated a bit so that they can be used with the "/e sitchair" emote

**Additional context**

    Add any details or screenshots or video recordings (including timestamps) that provide additional context

**Comment by dennrick** [comment]
Moving to in-progress as this is now under development/testing

**Comment by dennrick** [comment]
Closing as this has mostly been implemented
