### ISSUE TITLE
More female customizations to add to last ticket

### ISSUE THREAD

**Issue by themsgolightly** [dennrick/LineageRoleplay#39]
https://www.gta5-mods.com/player/louis-vuitton-bag-for-mp-female
https://www.gta5-mods.com/player/gucci-dress
https://www.gta5-mods.com/player/dior-necklace-for-mp-female
https://www.gta5-mods.com/player/short-fluffy-wavy-hair-for-mp-female
https://www.gta5-mods.com/player/round-prescription-glasses-pack-for-mp-female

**Comment by daddyDUBZ** [comment]
These have been added to the previous ticket.  We will close this ticket now.
