### ISSUE TITLE
Blaine savings Bank

### ISSUE THREAD

**Issue by GunnyCJ** [dennrick/LineageRoleplay#42]
i think the script is broken for the bank

**Describe the bug** *(A clear and detailed description of what the bug is):*
open safe door and no way using all available tools can not open gate to boxes

**To Reproduce** *(Steps to reproduce the behavior):*
  goto blaine county bank with security card open door and attemt to open gate

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Expected behavior details here...

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
The issue was found and fixed yesterday in PTR. Will be pushed live with the coming update.
