### ISSUE TITLE
[FEATURE] Missing Store near Paleto Benny's

### ISSUE THREAD

**Issue by overlordrockz** [dennrick/LineageRoleplay#43]
## [Feature Request]

**Is your feature request related to a problem?** *If so, describe in detail:*

    There is a convenience store marked on the map next to the Benny's repair garage.  There are cameras linked to this location as well and if you look at them, you will see the void below the map instead of an interior.

**Describe the solution you'd like to see:**

    I was wondering if it's possible to add an interior there so that the cameras aren't completely useless at that location

**Describe alternatives you've considered:**

    Alternatively, the cameras and marker could be removed if it's just easier to do that

**Additional context**

    Add any details or screenshots or video recordings (including timestamps) that provide additional context

**Comment by daddyDUBZ** [comment]
This issue is being addressed in an open ticket.

https://github.com/dennrick/LineageRoleplay/issues/17
