### ISSUE TITLE
[BUG] Mysterious Case of the Invisible Phone

### ISSUE THREAD

**Issue by PerfectLies86** [dennrick/LineageRoleplay#44]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

When phone is pulled out of pocket it is see through with the phone framing visible.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Open phone using M
    2. Phone Opens
    3. Nothing inside of phone framing loads
    4. Be sad that you can't see the Twitter drama
    5. Attempt to click on a ghost icon to see if anything works
    6. Nothing happens
    5. Close phone and repeat with same results

**Expected behavior** *(A clear and concise description of what you expected to happen):*

   When  opening phone, I would love to see my icons and be able to use my phone.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
   N/A

**Additional context** *(Add any other context about the problem here):*
    
 Carrie Cahill
CIT ID # IPB60407
5/2/2021
Approx 10:20 am CST
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
![image](https://user-images.githubusercontent.com/83547346/116819227-bc41a580-ab34-11eb-93f8-a193c03cd26c.png)

**Comment by PerfectLies86** [comment]
Resolved with logging in and out of the city.

**Comment by daddyDUBZ** [comment]
Keeping open for now for tracking

**Comment by dennrick** [comment]
were there any errors when this happened, @PerfectLies86

**Comment by PerfectLies86** [comment]
No Errors in the F8 menu @dennrick
