### ISSUE TITLE
[BUG] RELOADING STACKED FIREARMS

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#49]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    WHEN RELOADING STACKED FIREARMS ALL WEAPONS IN STACK RELOAD

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. STACK MULTIPLE PISTILS
    2. EQUIP THE WEAPON
    3. RELOAD
    4. UNSTACK WEAPONS

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    RELOADING SHOULD ONLY RELOAD 1 WEAPON IN THE STACK

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    BUG WAS DISCOVERED WHILE ON MY COP CHARACTER
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by MjrDeathAdder** [comment]
Prevented stacked guns.
