### ISSUE TITLE
Broken Gun

### ISSUE THREAD

**Issue by Cobra-Kai-RP** [dennrick/LineageRoleplay#51]
Infinite ammo with a broken gun

**Comment by daddyDUBZ** [comment]
This ticket is too vague for us to begin troubleshooting.  When submitting tickets please use the provided templates.   What events lead up to this discovery? Did the gun break and continue firing?   Did you reload a broken gun which resulted in the broken gun firing?  Does it fire with unlimited ammunition or unlimited magazines to reload?

**Comment by dennrick** [comment]
While this is vague I may have found the issue.  @Cobra-Kai-RP please be sure to use the proper template moving forward.
