### ISSUE TITLE
[FEATURE] New Dispatch System

### ISSUE THREAD

**Issue by dennrick** [dennrick/LineageRoleplay#7]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Converstion to cd_dispatch for all of our dispatching to allow for easier management.  Implement dispatch system across all whitelist jobs requiring calls including Taxi, Mechanics, EMS, Police.

Will change the text commands for emergency services:
/911 PD
/SOMETHING - EMS
/mechanic?? - Mechanics
/taxi ?? - Taxi

Requirements:
Alter the way callsigns work and are stored
Changes to the plist/mlist showing active units

**Describe alternatives you've considered**
N/A

**Additional context**
Planned change - under development - opened for tracking

**Comment by dennrick** [comment]
Currently under development.  Need to swap ESX functions for LNG functions.

Still need to look at the active unit lists and decide how we want to proceed.

**Comment by MjrDeathAdder** [comment]
Police notifications implimented
