### ISSUE TITLE
[BUG] not your apartment?

### ISSUE THREAD

**Issue by overlordrockz** [dennrick/LineageRoleplay#74]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    When you wake up in your apartment then leave it will give you the option to change apartments.  The bug goes away after you leave the area and come back but it can be annoying for some that forget things in their apartments when the first log in.

**To Reproduce** *(Steps to reproduce the behavior):*
  

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Expected behavior details here...

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
Don't forget things in your apartment...

**Comment by dennrick** [comment]
Confirmed bug.

Likely solution:  Move change apartments to a central location and add a fee for doing so but nothing outrageous.
Other solution:  Slightly move the prompt to change apartments if possible.
