### ISSUE TITLE
[BUG] Phone Prevents You From Doing Anything - Sploom

### ISSUE THREAD

**Issue by dennrick** [dennrick/LineageRoleplay#75]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    When you bring the phone up you are locked and not able to move/drive while using the phone.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Open Phone
    2. See Result

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Ability to still move and drive while using the phone

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your problem):*
    
    N/A

**Additional context** *(Add any other context about the problem here):*
    
    N/A
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    N/A

**Comment by MjrDeathAdder** [comment]
I'll have a look at the way it locks input and try to move the lock to just mouse until a text field is opened.
