### ISSUE TITLE
[SOP] Official Formation Of La Sacra Crime Family

### ISSUE THREAD

**Issue by Kouts3** [dennrick/LineageRoleplay#76]
## [SOP Request]

**General description of your SOP request:**

    La Sacra is a group of buddies who just wanna have fun. We've become more organized in recent weeks. We love the community of Lineage and hope to bring fun scenarios to the city. 

**Would people work/affiliate with this SOP?**

    Yes. We have 8 official members of the family already. With hopes to bring in more as we go. They have gone through an interview process and were vetted through an associate program first. 

**What permissions, scripts, interiors, special vehicles etc. are required?**

    We have been using the villa at 722 "La Fuente Blanca" as our main compound. If the interior could be tweaked a bit we'd love to discuss it. we have also found an MLO if its easier to use that. We are open to further discussion on this in more detail. We have also been using the Vineyard at 911 for our meetings/parties. The Vineyard is pretty good as is.

**SOP Request**

    https://docs.google.com/document/d/1uUVlf7wY5A0Udq-EpOAmfU2bcqXt5ro51liIzLMRDmc/edit#

**Comment by dennrick** [comment]
Closed - SOP ticket opened in Discord.
