### ISSUE TITLE
[FEATURE] Setting a Court date

### ISSUE THREAD

**Issue by overlordrockz** [dennrick/LineageRoleplay#77]
## [Feature Request]

**Is your feature request related to a problem?** *If so, describe in detail:*

    No, it is just just set a court date for a civil suit that my PD character was involved with. 

**Describe the solution you'd like to see:**

    I was hoping to have it set for Monday or Tuesday next week.  Although i could be later next week if it works better for all parties involved.

**Describe alternatives you've considered:**

    Enter details of alternative solutions here.

**Additional context**

   The people involved are myself, O-39 Devorah Frey (axel_blackthorne), Lou Siefer (oldsaltygrandpa), Antonio Genovese, R-1 Slade Reedson, R-5 Pheonix Stark, and Cobra Kai.

**Comment by dennrick** [comment]
Please open a Help Me ticket on the forums for this @overlordrockz
