### ISSUE TITLE
[BUG] "Locked" doors

### ISSUE THREAD

**Issue by overlordrockz** [dennrick/LineageRoleplay#78]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    There are a few doors in the city that I've noticed that you can enter the interior of the building while the door is locked but you cant get out. I personally witnessed the doors at MRPD do this. The garage doors will also open even when locked but will stay open while you are in the garage.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Go to MRPD
    2. Walk up to any door
    3. Go though said door without unlocking it

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    You would be unable to cross the threshold past a locked door

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
Please refer to #79 for tracking on the doorlock issues.
