### ISSUE TITLE
[BUG] Crayola MC Gate Not Locking

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#79]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

> Clubhouse gate not  locking

**To Reproduce** *(Steps to reproduce the behavior):*
  
> 1. Go to gate
2. lock gate  gate shows locked.  but gate opens for players and locals
 

**Expected behavior** *(A clear and concise description of what you expected to happen):*

> Gate should lock and not open

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
> NA

**Additional context** *(Add any other context about the problem here):*
    
> 12:19 PM] RandomCam93: the front gate to the MC club at 567 says its locked but well open automatically when you pull up in front of it even after i unlock it and lock it back up
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by daddyDUBZ** [comment]
This issue is affecting other locking gates or overhead doors as well

**Comment by dennrick** [comment]
Appears to be happening across all doors, currently.

**Comment by dennrick** [comment]
Closing as this was resolved in a hotfix.
