### ISSUE TITLE
[BUG] People Able To Use Phone When Downed

### ISSUE THREAD

**Issue by Cobra-Kai-RP** [dennrick/LineageRoleplay#84]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    People are able to use their phones when they are down.

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Down a person
    2. Use 'M' to open phone

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Phone should not open when down

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
I disagree that you shouldn't be able to use your phone if you are in the Last Stand phase.  You aren't considered dead at this point and can chat/interact with others.

However, after that initial last stand phase then I agree you shouldn't be able to use chat commands or any items.

**Comment by Quagel** [comment]
You are currently able to open and text on the phone but unable to use the radio or speak on calls when in Last Stand. Whatever is desired is currently inconsistent.

**Comment by dennrick** [comment]
Fixed in 4am EDT Update.

New method is consistent so when you die you are removed from the radio, prevented from talking, and cannot open your phone.
