### ISSUE TITLE
[BUG] Radio Disconnect on death

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#87]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

> radio remains connected after death

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1. Die while connected to radio

**Expected behavior** *(A clear and concise description of what you expected to happen):*

> Radio should disconnect because radio is removed from inventory.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    Links to video clips go here (include time stamps if necessary)...

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by MjrDeathAdder** [comment]
This is post respawn at pillbox yes?

**Comment by dennrick** [comment]
This is now resolved with 6/27 patches and swtitch to pma-voice
