### ISSUE TITLE
The Crew - Gang SOP

### ISSUE THREAD

**Issue by drunkpilot96** [dennrick/LineageRoleplay#90]
## [SOP Request]

**General description of your SOP request:**

    The crew would like to officially establish themselves as a gang within the city.

**Would people work/affiliate with this SOP?**

    Yes, members of the crew (listed in doc) work in various ways with many people around the city already. 

**What permissions, scripts, interiors, special vehicles etc. are required?**

  Gang menu with society fund, stash and a crew house/clubhouse as defined in the google doc. Open to discussion about any of it as well.
https://forum.cfx.re/t/mlo-devin-westons-mansion-interior-paid-resource/1921220

**SOP Request**

https://docs.google.com/document/d/1MdIyZ56we6BkOtJyBkVseP1op5ixdW8fXnuWLzx5AAk/edit

**Comment by dennrick** [comment]
Closing for now
