### ISSUE TITLE
[BUG] Anonymous Tweets

### ISSUE THREAD

**Issue by Quagel** [dennrick/LineageRoleplay#92]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

    Anonymous Tweets are no longer working post update. Unsure if this is intentional or a bug. If intentional an update to the 
    DIscord would be desirable have had multiple players make this mistake without knowing

**To Reproduce** *(Steps to reproduce the behavior):*
  
    1) Enable Anonymous mode on cell phone
    2) Send tweet
    3) Check sender in feed

**Expected behavior** *(A clear and concise description of what you expected to happen):*

    Tweets sent anonymously when in anonymous mode and as player when not anonymous.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    N/A.

**Additional context** *(Add any other context about the problem here):*
    
    N/A.
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    N/A.

**Comment by dennrick** [comment]
Will take a look into this but we were planning on removing the anonymous tweets and calls anyway.

**Comment by dennrick** [comment]
Confirmed not bringing this back.
