### ISSUE TITLE
[FEATURE]Repair kits

### ISSUE THREAD

**Issue by dennrick** [dennrick/LineageRoleplay#94]
**DISCORD ID**: 
> shaggydoclip#2576

**TIME STAMP**: 
> 5/20/2021 14:13:05

**IS FEATURE RELATED TO A PROBLEM? EXPLAIN. **: 
> no

**DESCRIBE YOUR SOLUTION**: 
> i would like to use advance repair kits around the shop to repair cars fully so that way we don't have a line car waiting to get repaired 

**DESCRIBE ALTERNATIVE SOLUTIONS**: 
> allow mechanic on duty to repair anywhere on the shop and using the bay for upgrades only

**ADDITIONAL CONTEXT**: 
> if caught outside the shop with advance repair kits will be removed from the mechanics permanently  

**VOD/SCREENSHOT LINKS**: 
> 

**SCREENSHOT UPLOADS**: 
>

**Comment by daddyDUBZ** [comment]
**This addition would allow mechanics to RP repairing cars in the shop while modifications are being done in the only available mod bay. **

> An alternative solution which I would like to see instead is that mechanics have use of the  mechanic function on the F1 wheel so long as they are on duty and have tools in their pocket.  If they are off duty or dont have tools they should not be able to use the function.
