### ISSUE TITLE
[BUG] LPVM BUG IN PTR

### ISSUE THREAD

**Issue by daddyDUBZ** [dennrick/LineageRoleplay#96]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*

> LPVM Mod glitch in ptr

**To Reproduce** *(Steps to reproduce the behavior):*
  
> 1. Connect to ptr with LPVM enabled
2. Character glitches seemingly jumping every few seconds

**Expected behavior** *(A clear and concise description of what you expected to happen):*

No glitchy

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your problem):*
    
https://www.dropbox.com/s/01c94o8oabj1sy2/mz0lYYqEHq.mp4?dl=0

**Additional context** *(Add any other context about the problem here):*
    
    Put any additional details that offer additional context here...
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    Screenshots go here...

**Comment by dennrick** [comment]
I don't believe this is LPVM related. Assuming it has to do with the anti-fall through the map stuff I'm testing.

**Comment by dennrick** [comment]
Should now be resolved.
